[project]
name = "lm-agents-hw-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "John Guerrerio", email = "johnjguerrerio@gmail.com" }
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "datasets>=5.0.1",
    "iprogress>=0.4",
    "matplotlib>=3.11.2",
    "peft>=0.21.0",
    "tqdm>=4.70.1",
    "transformers>=5.17.0",
    "vllm>=0.30.0",
]

[project.scripts]
lm-agents-hw-1 = "lm_agents_hw_1:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false
